# Generated by Django 6.0.2 on 2026-02-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
